const MetWithData = [
    {
        id: 1,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Shubham Singh",
        secondPersonName:"Anmol rawat",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 2,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Robert",
        secondPersonName:"James",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 3,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Natasha",
        secondPersonName:"Steav",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 4,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Peter",
        secondPersonName:"Jerome Brewer",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 5,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Winona Jennings",
        secondPersonName:"Roman",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 6,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Brock",
        secondPersonName:"John",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 7,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Kevin",
        secondPersonName:"RKO",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
    {
        id: 8,
        firstPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg",
        firstPersonName:"Tom",
        secondPersonName:"Holland",
        time:"Jun 25 2021",
        secondPersonDP:"https://lunchclub.com/static/media/default-picture.90b9161a.svg", 
        aboutSecondPerson:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod commodi quibusdam harum aspernatur et debitis tempore aliquam atque corrupti laborum.",
    },
];
export default MetWithData;